// src/components/Demos/basic/binding.vue
<script setup>
  import { ref, onMounted, onUnmounted } from 'vue';
  import RangeSlider from 'svelte-range-slider-pips';

  const value = ref(10);
  const $node = ref(null);
  let MyRangeSlider = ref(null);

  const updateSlider = () => {
    MyRangeSlider.$set({ value: value.value });
  }

  onMounted(() => {
    MyRangeSlider = new RangeSlider({ 
      target: $node.value,
      props: {
        min: 0,
        max: 100,
        value: value.value
      }
    });

    MyRangeSlider.$on('change', (e) => {
      value.value = e.detail.value;
    });
  });

  onUnmounted(() => {
    if (MyRangeSlider) {
      MyRangeSlider.$destroy();
    }
  });
</script>

<template>
  <div id="binding-slider" ref="$node"></div>
  <input type="number" v-model="value" @change="updateSlider" />
</template>

// src/components/Demos/basic/binding.jsx
import { useEffect, useRef, useState } from 'react';
import RangeSlider from 'svelte-range-slider-pips';

export default function BasicBinding() {
  const [value, setValue] = useState(10);
  const nodeRef = useRef(null);
  const sliderRef = useRef(null);

  useEffect(() => {
    sliderRef.current = new RangeSlider({
      target: nodeRef.current,
      props: {
        min: 0,
        max: 100,
        value: value,
      },
    });

    sliderRef.current.$on('change', (e) => {
      setValue(e.detail.value);
    });

    return () => {
      if (sliderRef.current) {
        sliderRef.current.$destroy();
      }
    };
  }, [value]);

  useEffect(() => {
    if (sliderRef.current) {
      sliderRef.current.$set({ value });
    }
  }, [value]);

  return (
    <div>
      <div id="binding-slider" ref={nodeRef}></div>
      <input type="number" value={value} onChange={(e) => setValue(e.target.valueAsNumber)} />
    </div>
  );
}
