// src/components/Demos/basic/typical.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue';
import RangeSlider from 'svelte-range-slider-pips';

const values = ref([10, 50]);
const $node = ref(null);
let MyRangeSlider = ref(null);

onMounted(() => {
  MyRangeSlider = new RangeSlider({
    target: $node.value,
    props: {
      values: values.value,
      pips: true,
      float: true,
      first: 'label',
      last: 'label',
    },
  });

  MyRangeSlider.$on('change', (e) => {
    values.value = e.detail.values;
  });
});

onUnmounted(() => {
  if (MyRangeSlider) {
    MyRangeSlider.$destroy();
  }
});
</script>

<template>
  <div ref="$node"></div>
</template>

// src/components/Demos/basic/typical.jsx
import { useEffect, useRef, useState } from 'react';
import RangeSlider from 'svelte-range-slider-pips';

export default function TypicalUsage() {
  const [values, setValues] = useState([10, 50]);
  const nodeRef = useRef(null);
  const sliderRef = useRef(null);

  useEffect(() => {
    sliderRef.current = new RangeSlider({
      target: nodeRef.current,
      props: {
        values: values,
        pips: true,
        float: true,
        first: 'label',
        last: 'label'
      }
    });

    sliderRef.current.$on('change', (e) => {
      setValues(e.detail.values);
    });

    return () => {
      if (sliderRef.current) {
        sliderRef.current.$destroy();
      }
    };
  }, [values]);

  return (
    <div ref={nodeRef}></div>
  );
}
