// src/components/Demos/basic/useless.jsx
import { useEffect, useRef } from 'react';
import RangeSlider from 'svelte-range-slider-pips';

export default function UselessSlider() {
  const nodeRef = useRef(null);
  const sliderRef = useRef(null);

  useEffect(() => {
    sliderRef.current = new RangeSlider({
      target: nodeRef.current,
    });

    return () => {
      // Cleanup if needed
      if (sliderRef.current) {
        sliderRef.current.$destroy();
      }
    };
  }, []);

  return <div id="useless-slider" ref={nodeRef}></div>;
}

// src/components/Demos/basic/useless.vue
<script setup>
  import { ref, onMounted, onUnmounted } from 'vue';
  import RangeSlider from 'svelte-range-slider-pips';

  const $node = ref(null);
  let MyRangeSlider = ref(null);

  onMounted(() => {
    MyRangeSlider = new RangeSlider({ 
      target: $node.value
    });
  });

  onUnmounted(() => {
    if (MyRangeSlider) {
      MyRangeSlider.$destroy();
    }
  });
</script>

<template>
  <div id="useless-slider" ref="$node"></div>
</template>
